[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1fbBLiJ76yyYsjLYKXQ-IWpthk-tAS3dUloluI4qQDtg/edit"
type = "service_account"
project_id = "database-rekap-pengadaan"
private_key_id = "104eda83d585ac9ef904a5fc773fc8ac4a401caa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3jWfZjY/g9PF+
BZf9bMVUJmWu6/cIRCTWMHkBabfs6oOdUzwQYoQzj5r8tpq82l8MojPaXKhJU1w+
coSg8B+1Ow7yfe4iDqH3/w9AO89FpAp1DPdzZWp5kv09srjl6raLHljJMRDyCyap
r9yqOB8x2s0/uud3U9fZ0VcirT2Rc1QZHWYhi/2qn+59zzz6Zv+HaR6PhRdsqk7o
0PuTqsoiZbIed6L0/OIPFdhWs8OU6Cu4st/VtVWd8nXq8Y4Hn121jF58+b3kAzj3
28m9czxfiiEU+Cm7KJHnv7UWItWygCS+e9q3erho9A75+tYg1mwuEGETqt1YNRQJ
/4yAbq73AgMBAAECgf9dkTffLsqpYjO4iiFwjoII44nyIVdMX3Bnv03v6nRX0TRG
fqefspixsALR0EQRAUBysDy+k30148iiDL6PS9jeCb0U4B0EP3FRejPMCrEeTwEF
qhZ6PLiKQOPXD8Qxb/Sd9lpMNTbuK8EJvxw9qV49i8wVMLHNom/mGVDR3H4GJmXP
KTpySgTB8P0W+z89WB/uXLOBJ9ca7NAiFc0Wk4QUPJaCicBOc9L0uXDnxLrCt0tQ
ZtRrd/9PijqVm/5CVTz6NQ0A5yXl1vP0X+Y5VmvHgYEzQIAqI74wwyb1009owwM+
ybr4M8vtQ7OjlOqQs9MxixmxbiFbkhpmjPB+gtkCgYEA8qYYKz04RfcOXpdbitNs
8PXw4fCHUhC98jRdWA0JGjHqQjwUFerzG5YKuGgKGTqErtZZ5OpQ5M0bWKSZhn21
8thI1u7K9jw18KJKhdKpdzMbTueMrIxSv1TgEX16b9eRuN4SV2ZBA0vub6W9caXR
tmlzgFUdEa7xGlaPooGT3/8CgYEAwabjzsnPX1V8ez3OQOvyeeu7p8to/MFpFvNs
5t0vtIn6nnsnNRF8RySYkXSgksF75sGYc+nTcESBtBSjZvBCre8GqXix6mA5d9F9
718LM8eMq4UxOasgjElM0j17urpsH1tolHecQCPEonYDahPMCVf/XdQSjki/o3Fr
UtukMQkCgYBhAxsCnpVTE7WBCA6ncGRL6miGTL4th1gJ7/mp7HxJJs+7730wTiEo
VFKw65euAoFtzXFfXnc9IuveAuEGrlgCYYqttAcdb3E5ZglZe6IZcCto3paVnfyv
VmXHWF2NPaibOt4mZ1Fy2fbYWHFncJ5pybtOAbl/imwG1bjThe7zTQKBgQCb3AGg
Lqdb+Ibe/iih8gVPgZ6gd0PBor09PqDY0w8RRLhUk5RDzxXygI7XC0Itu9JIMGrO
aFTIGCs4UCAPurJAIZCAF+dCVz4JpK+yWBHBFAuxBNtQqd3hayGMWPXbnS1ms4Bh
ndj9pFCCwDUHEP7jJkGy1DPn+UKkFGEUkBCmLWQKBgQCxlldmZca+Gj2bcDUob/W6
/nFony9YLBBDCvENdkFcAGmOA6hCGejEt7vhYODmkxsJw+OXkYLbmtaACRdqi4gu
h5ekPEDX6HOcAmQEit/154aYrpYHGmjKK1MdNKOlhSbC3TX+iKTe5CFTGDI7KdJ4
f762OcTr0Bq4YWC+KBAz8Q==
-----END PRIVATE KEY-----"""
client_email = "database-rekap-pengadaan@database-rekap-pengadaan.iam.gserviceaccount.com"
client_id = "116139330030675855871"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/database-rekap-pengadaan%40database-rekap-pengadaan.iam.gserviceaccount.com"
